// Comprehensive Indian states and cities data (sample, expand as needed)
export const indianStatesCities = {
    "Delhi": [
      "Central Delhi",
      "East Delhi",
      "North Delhi",
      "North East Delhi",
      "North West Delhi",
      "South Delhi",
      "South West Delhi",
      "West Delhi"
    ],
    "Haryana": [
      "Ambala",
      "Bhiwani",
      "Faridabad",
      "Fatehabad",
      "Gurgaon",
      "Hisar",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Karnal",
      "Kurukshetra",
      "Mahendragarh",
      "Panchkula",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamuna Nagar"
    ],
    "Punjab": [
      "Amritsar",
      "Barnala",
      "Bathinda",
      "Faridkot",
      "Fatehgarh Sahib",
      "Fazilka",
      "Firozpur",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Ludhiana",
      "Mansa",
      "Moga",
      "Mohali",
      "Muktsar",
      "Nawanshahr",
      "Pathankot",
      "Patiala",
      "Ropar",
      "Rupnagar",
      "Sangrur",
      "Tarn Taran"
    ],
    "Chandigarh": [
      "Chandigarh"
    ],
    "Himachal Pradesh": [
      "Bilaspur (HP)",
      "Chamba",
      "Hamirpur(HP)",
      "Kangra",
      "Kinnaur",
      "Kullu",
      "Lahul & Spiti",
      "Mandi",
      "Shimla",
      "Sirmaur",
      "Solan",
      "Una"
    ],
    "Jammu & Kashmir": [
      "Ananthnag",
      "Bandipur",
      "Baramulla",
      "Budgam",
      "Doda",
      "Jammu",
      "Kargil",
      "Kathua",
      "Kulgam",
      "Kupwara",
      "Leh",
      "Poonch",
      "Pulwama",
      "Rajauri",
      "Reasi",
      "Srinagar",
      "Udhampur"
    ],
    "Uttar Pradesh": [
      "Agra",
      "Aligarh",
      "Allahabad",
      "Ambedkar Nagar",
      "Auraiya",
      "Azamgarh",
      "Bagpat",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Barabanki",
      "Bareilly",
      "Basti",
      "Bijnor",
      "Budaun",
      "Bulandshahr",
      "Chandauli",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Etawah",
      "Faizabad",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Gautam Buddha Nagar",
      "Ghaziabad",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Jyotiba Phule Nagar",
      "Kannauj",
      "Kanpur Dehat",
      "Kanpur Nagar",
      "Kaushambi",
      "Kheri",
      "Kushinagar",
      "Lalitpur",
      "Lucknow",
      "Maharajganj",
      "Mahoba",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "Raebareli",
      "Rampur",
      "Saharanpur",
      "Sant Kabir Nagar",
      "Sant Ravidas Nagar",
      "Shahjahanpur",
      "Shrawasti",
      "Siddharthnagar",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi"
    ],
    "Uttarakhand": [
      "Almora",
      "Bageshwar",
      "Chamoli",
      "Champawat",
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Pauri Garhwal",
      "Pithoragarh",
      "Rudraprayag",
      "Tehri Garhwal",
      "Udham Singh Nagar",
      "Uttarkashi"
    ],
    "Rajasthan": [
      "Ajmer",
      "Alwar",
      "Banswara",
      "Baran",
      "Barmer",
      "Bharatpur",
      "Bhilwara",
      "Bikaner",
      "Bundi",
      "Chittorgarh",
      "Churu",
      "Dausa",
      "Dholpur",
      "Dungarpur",
      "Ganganagar",
      "Hanumangarh",
      "Jaipur",
      "Jaisalmer",
      "Jalor",
      "Jhalawar",
      "Jhujhunu",
      "Jodhpur",
      "Karauli",
      "Kota",
      "Nagaur",
      "Pali",
      "Rajsamand",
      "Sawai Madhopur",
      "Sikar",
      "Sirohi",
      "Tonk",
      "Udaipur"
    ],
    "Gujarat": [
      "Ahmedabad",
      "Amreli",
      "Anand",
      "Banaskantha",
      "Bharuch",
      "Bhavnagar",
      "Dahod",
      "Gandhi Nagar",
      "Jamnagar",
      "Junagadh",
      "Kachchh",
      "Kheda",
      "Mahesana",
      "Narmada",
      "Navsari",
      "Panch Mahals",
      "Patan",
      "Porbandar",
      "Rajkot",
      "Sabarkantha",
      "Surat",
      "Surendra Nagar",
      "The Dangs",
      "Vadodara",
      "Valsad"
    ],
    "Daman & Diu": [
      "Daman",
      "Diu"
    ],
    "Dadra & Nagar Haveli": [
      "Dadra & Nagar Haveli"
    ],
    "Maharashtra": [
      "Ahmed Nagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Beed",
      "Bhandara",
      "Buldhana",
      "Chandrapur",
      "Dhule",
      "Gadchiroli",
      "Gondia",
      "Hingoli",
      "Jalgaon",
      "Jalna",
      "Kolhapur",
      "Latur",
      "Mumbai",
      "Nagpur",
      "Nanded",
      "Nandurbar",
      "Nashik",
      "Osmanabad",
      "Parbhani",
      "Pune",
      "Raigarh(MH)",
      "Ratnagiri",
      "Sangli",
      "Satara",
      "Sindhudurg",
      "Solapur",
      "Thane",
      "Wardha",
      "Washim",
      "Yavatmal"
    ],
    "Goa": [
      "North Goa",
      "South Goa"
    ],
    "Madhya Pradesh": [
      "Anuppur",
      "Ashok Nagar",
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Burhanpur",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Dewas",
      "Dhar",
      "Dindori",
      "East Nimar",
      "Guna",
      "Gwalior",
      "Hoshangabad",
      "Indore",
      "Jabalpur",
      "Jhabua",
      "Katni",
      "Khandwa",
      "Mandla",
      "Mandsaur",
      "Morena",
      "Narsinghpur",
      "Neemuch",
      "Panna",
      "Raisen",
      "Rajgarh",
      "Ratlam",
      "Rewa",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sheopur",
      "Shivpuri",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Umaria",
      "Vidisha",
      "West Nimar"
    ],
    "Chattisgarh": [
      "Bastar",
      "Bijapur(CGH)",
      "Bilaspur(CGH)",
      "Dantewada",
      "Dhamtari",
      "Durg",
      "Gariaband",
      "Janjgir-champa",
      "Jashpur",
      "Kanker",
      "Kawardha",
      "Korba",
      "Koriya",
      "Mahasamund",
      "Narayanpur",
      "Raigarh",
      "Raipur",
      "Rajnandgaon",
      "Surguja"
    ],
    "Telangana": [
      "Adilabad",
      "Hyderabad",
      "K.V.Rangareddy",
      "Karim Nagar",
      "Khammam",
      "Mahabub Nagar",
      "Medak",
      "Nalgonda",
      "Nizamabad",
      "Warangal"
    ],
    "Andhra Pradesh": [
        "Srikakulam",
        "Parvathipuram Manyam",
        "Vizianagaram",
        "Visakhapatnam",
        "Alluri Sitharama Raju",
        "Anakapalli",
        "Kakinada",
        "East Godavari",
        "Dr. B. R. Ambedkar Konaseema",
        "Eluru",
        "West Godavari",
        "NTR",
        "Krishna",
        "Palnadu",
        "Guntur",
        "Bapatla",
        "Sri Potti Sriramulu Nellore",
        "Prakasam",
        "Kurnool",
        "Nandyal",
        "Ananthapuramu",
        "Sri Sathya Sai",
        "YSR Kadapa",
        "Annamayya",
        "Tirupati",
        "Chittoor"
    ],
    "Karnataka": [
      "Bagalkot",
      "Bangalore",
      "Bangalore Rural",
      "Belgaum",
      "Bellary",
      "Bidar",
      "Bijapur(KAR)",
      "Chamrajnagar",
      "Chickmagalur",
      "Chikkaballapur",
      "Chitradurga",
      "Dakshina Kannada",
      "Davangere",
      "Dharwad",
      "Gadag",
      "Gulbarga",
      "Hassan",
      "Haveri",
      "Kodagu",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysore",
      "Raichur",
      "Ramanagar",
      "Shimoga",
      "Tumkur",
      "Udupi",
      "Uttara Kannada",
      "Yadgir"
    ],
    "Tamil Nadu": [
      "Ariyalur",
      "Chennai",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Kanchipuram",
      "Kanyakumari",
      "Karur",
      "Krishnagiri",
      "Madurai",
      "Nagapattinam",
      "Namakkal",
      "Nilgiris",
      "Perambalur",
      "Pudukkottai",
      "Ramanathapuram",
      "Salem",
      "Sivaganga",
      "Thanjavur",
      "Theni",
      "Tiruchirappalli",
      "Tirunelveli",
      "Tiruvallur",
      "Tiruvannamalai",
      "Tiruvarur",
      "Tuticorin",
      "Vellore",
      "Villupuram",
      "Virudhunagar"
    ],
    "Pondicherry": [
      "Karaikal",
      "Pondicherry"
    ],
    "Kerala": [
      "Alappuzha",
      "Ernakulam",
      "Idukki",
      "Kannur",
      "Kasargod",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Palakkad",
      "Pathanamthitta",
      "Thiruvananthapuram",
      "Thrissur",
      "Wayanad"
    ],
    "Lakshadweep": [
      "Lakshadweep"
    ],
    "West Bengal": [
      "Bankura",
      "Bardhaman",
      "Birbhum",
      "Cooch Behar",
      "Darjiling",
      "East Midnapore",
      "Hooghly",
      "Howrah",
      "Jalpaiguri",
      "Kolkata",
      "Malda",
      "Murshidabad",
      "Nadia",
      "North 24 Parganas",
      "North Dinajpur",
      "Puruliya",
      "South 24 Parganas",
      "South Dinajpur",
      "West Midnapore"
    ],
    "Sikkim": [
      "East Sikkim",
      "North Sikkim",
      "South Sikkim",
      "West Sikkim"
    ],
    "Andaman & Nicobar": [
      "Nicobar",
      "North And Middle Andaman",
      "South Andaman"
    ],
    "Odisha": [
      "Angul",
      "Balangir",
      "Baleswar",
      "Bargarh",
      "Bhadrak",
      "Boudh",
      "Cuttack",
      "Debagarh",
      "Dhenkanal",
      "Gajapati",
      "Ganjam",
      "Jagatsinghapur",
      "Jajapur",
      "Jharsuguda",
      "Kalahandi",
      "Kandhamal",
      "Kendrapara",
      "Kendujhar",
      "Khorda",
      "Koraput",
      "Malkangiri",
      "Mayurbhanj",
      "Nabarangapur",
      "Nayagarh",
      "Nuapada",
      "Puri",
      "Rayagada",
      "Sambalpur",
      "Sonapur",
      "Sundergarh"
    ],
    "Assam": [
      "Barpeta",
      "Bongaigaon",
      "Cachar",
      "Darrang",
      "Dhemaji",
      "Dhubri",
      "Dibrugarh",
      "Goalpara",
      "Golaghat",
      "Hailakandi",
      "Jorhat",
      "Kamrup",
      "Karbi Anglong",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Marigaon",
      "Nagaon",
      "Nalbari",
      "North Cachar Hills",
      "Sibsagar",
      "Sonitpur",
      "Tinsukia"
    ],
    "Meghalaya": [
      "East Garo Hills",
      "East Khasi Hills",
      "Jaintia Hills",
      "Ri Bhoi",
      "South Garo Hills",
      "West Garo Hills",
      "West Khasi Hills"
    ],
    "Arunachal Pradesh": [
      "Changlang",
      "Dibang Valley",
      "East Kameng",
      "East Siang",
      "Kurung Kumey",
      "Lohit",
      "Lower Dibang Valley",
      "Lower Subansiri",
      "Papum Pare",
      "Tawang",
      "Tirap",
      "Upper Siang",
      "Upper Subansiri",
      "West Kameng",
      "West Siang"
    ],
    "Manipur": [
      "Bishnupur",
      "Chandel",
      "Churachandpur",
      "Imphal East",
      "Imphal West",
      "Senapati",
      "Tamenglong",
      "Thoubal",
      "Ukhrul"
    ],
    "Mizoram": [
      "Aizawl",
      "Champhai",
      "Kolasib",
      "Lawngtlai",
      "Lunglei",
      "Mammit",
      "Saiha",
      "Serchhip"
    ],
    "Nagaland": [
      "Dimapur",
      "Kiphire",
      "Kohima",
      "Longleng",
      "Mokokchung",
      "Mon",
      "Peren",
      "Phek",
      "Tuensang",
      "Wokha",
      "Zunhebotto"
    ],
    "Tripura": [
      "Dhalai",
      "North Tripura",
      "South Tripura",
      "West Tripura"
    ],
    "Bihar": [
      "Araria",
      "Arwal",
      "Aurangabad(BH)",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Bhojpur",
      "Buxar",
      "Darbhanga",
      "East Champaran",
      "Gaya",
      "Gopalganj",
      "Jamui",
      "Jehanabad",
      "Kaimur (Bhabua)",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Lakhisarai",
      "Madhepura",
      "Madhubani",
      "Munger",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia",
      "Rohtas",
      "Saharsa",
      "Samastipur",
      "Saran",
      "Sheikhpura",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Vaishali",
      "West Champaran"
    ],
    "Jharkhand": [
      "Bokaro",
      "Chatra",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "East Singhbhum",
      "Garhwa",
      "Giridh",
      "Godda",
      "Gumla",
      "Hazaribag",
      "Jamtara",
      "Koderma",
      "Latehar",
      "Lohardaga",
      "Pakur",
      "Palamau",
      "Ramgarh",
      "Ranchi",
      "Sahibganj",
      "Seraikela-kharsawan",
      "Simdega",
      "West Singhbhum"
    ]
  };

// Utility: Get all states
export function getAllStates() {
  return Object.keys(indianStatesCities).map((stateName) => ({ 
    code: stateName, 
    name: stateName 
  }));
}

// Utility: Get cities by state name
export function getCitiesByState(stateName: string) {
  const cities = indianStatesCities[stateName as keyof typeof indianStatesCities];
  return cities ? cities.map((cityName) => ({ name: cityName, state: stateName })) : [];
}

// Utility: Autocomplete city
export function autocompleteCity(stateName: string, query: string) {
  const cities = getCitiesByState(stateName);
  if (!query) return cities;
  return cities.filter((c) => c.name.toLowerCase().includes(query.toLowerCase()));
} 